---
- name: Ansible with Linux
  hosts: node1
  become: true
  tasks:
    - name: Create User
      community.postgresql.postgresql_user:
        name: luisj
        password: luisj
        superuser: yes
        role_attr_flags: LOGIN, CREATEDB