--- 
- name: Ansible with Linux  
  hosts: node1
  become: true
  tasks:

    - name: Initialize the PostgreSQL data directory
      command: /usr/bin/postgresql-setup --initdb

    - name: Enable and activate the PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true