---
- name: Ansible with Linux
  hosts: node1
  become: true

  tasks:
    - name: Add a line in the file /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}"
